routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

// Route::middleware(['auth'])->group(function () {
//    Route::get('/', function () {
//    	return view('layouts.admin.admin');
//	 	});
// });

Route::middleware(['auth'])->group(function () {
	Route::get('/', 'DashboardController@index');
	// Route::get('/', function() {
	// 	return view('layouts.admin.admin');
	// });
});

Route::group([
	'prefix' =>'/master',
	'middleware'=>'auth'
], function(){

	Route::post('user/delete', ['as'=>'master.user.delete', 'uses'=>'UserController@delete']);
	Route::get('user/password/{id}',['as'=>'master.user.password.edit','uses'=>'UserController@editPassword']);
	Route::patch('user/password/{id}',['as'=>'master.user.password.update','uses'=>'UserController@updatePassword']);
	Route::resource('user', 'UserController',['as'=>'master']);

	Route::post('permission/delete', ['as'=>'master.permission.delete', 'uses'=>'PermissionController@delete']);
	Route::resource('permission', 'PermissionController',['as'=>'master']);

	Route::post('bank/delete', ['as'=>'master.bank.delete', 'uses'=>'BankController@delete']);
	Route::resource('bank', 'BankController',['as'=>'master']);

	Route::post('supplier/delete', ['as'=>'master.supplier.delete', 'uses'=>'SupplierController@delete']);
	Route::resource('supplier', 'SupplierController', ['as'=>'master']);

	Route::post('customer/delete', ['as'=>'master.customer.delete', 'uses'=>'CustomerController@delete']);
	Route::resource('customer', 'CustomerController', ['as'=>'master']);

	Route::post('employee/delete', ['as'=>'master.employee.delete', 'uses'=>'EmployeeController@delete']);
	Route::resource('employee', 'EmployeeController', ['as'=>'master']);
});

Route::group([
	'middleware' => 'auth'
], function() {
	Route::resource('colorant', 'ColorantController', ['as'=>'inventory']);
	Route::resource('paint', 'PaintController', ['as'=>'inventory']);

	Route::resource('inventory', 'InventoryController');
	Route::resource('inventorycategory', 'InventoryCategoryController', ['as'=>'master']);

	Route::post('merk/delete', ['as'=>'master.merk.delete', 'uses'=>'MerkController@delete']);
	Route::resource('merk', 'MerkController', ['as'=>'master']);

	Route::post('type/delete', ['as'=>'master.type.delete', 'uses'=>'TypeController@delete']);
	Route::resource('type', 'TypeController', ['as'=>'master']);
});



Route::group([
	'middleware'=>'auth',
], function(){
	Route::resource('cash', 'CashController');
});


// Purchasing
Route::resource('purchasing/order','PurchasingOrderController')->names('purchasing.order');
Route::get('purchasing/print/{id}', ['as'=>'purchasing.print', 'uses'=>'PurchasingController@printPDF']);
Route::resource('purchasing', 'PurchasingController');
Route::group([
	'prefix'=>'purchasing',
	// 'middleware'=>'auth',
], function(){
	Route::get('/payment/{id}', ['as'=>'purchasing.payment.create', 'uses'=>'PurchasingPaymentController@create']);
	Route::post('/payment', ['as'=>'purchasing.payment.store', 'uses'=>'PurchasingPaymentController@store']);
	Route::get('/retur/{id}',['as'=>'purchasing.retur.create','uses'=>'PurchasingReturController@create']);
	Route::post('/retur',['as'=>'purchasing.retur.store','uses'=>'PurchasingController@storeRetur']);
});


//Sales
Route::group([
	'prefix'=>'sales',
	// 'middleware'=>'auth',
], function(){
	Route::get('/send/{id}', ['as'=>'sales.send.create', 'uses'=>'SalesController@salesSend']);

	Route::get('/payment/{id}', ['as'=>'sales.payment.create', 'uses'=>'SalesPaymentController@create']);
	Route::post('/payment', ['as'=>'sales.payment.store', 'uses'=>'SalesPaymentController@store']);

	Route::resource('order', 'SalesOrderController',['as'=>'sales']);
});
Route::get('sales/print/{id}', ['as'=>'sales.print', 'uses'=>'SalesController@printPDF']);
Route::resource('sales', 'SalesController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Colorant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Colorant extends Model
{
    protected $fillable = ['colorant_code', 'name', 'merk', 'unit_stock', 'capacity', 'min_capacity', 'max_capacity', 'description'];

    public function merks()
    {
    	return $this->belongsTo('App\Merk', 'merk', 'alias');
    }
}

app/Http/Controllers/Api/ColorantController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ColorantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/InventoryController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Inventory;
use App\InventoryDiscount;
use App\InventoryPrice;
use App\InventoryConvert;
use App\InventoryQuantity;
use App\PurchasingDetail;
use App\Type;
use App\Merk;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Validator;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Inventory::all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    public function selector($id)
    {
        $type_list = Type::where('merk_id', $id)->pluck('name', 'alias');
        return json_encode($type_list);
    }

    public function selectoredit($id)
    {
        $type_edit = Type::where('name', $id)->pluck('name', 'alias');
        return json_encode($type_edit);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        $price_type = $request->price;
        
        $date = empty($request->date) ? date('Y-m-d') : $request->date;

        $inventory = Inventory::with(['prices'=>function($query) use ($request, $date, $price_type){
                $query->whereDate('created_at','<=',$date);
                $query->orderBy('created_at','desc');
                $query->where('price_type', $price_type);
            }])
            ->with('converts')
            ->where('inventory_code',$id)->first();

            $inventory = Inventory::with('converts')
                        ->where('inventory_code',$id)
                        ->first();
                    
        if (!$inventory) {
            return Response::json([
                'error'=>true,
                'message'=>'Cannot get Inventory',
                'code'=> 500
            ], 500);
        }else{
            return Response::json([
                'error'=>false,
                'message'=>'Successfuly get Inventory',
                'code'=>200,
                'data'=>$inventory
            ], 200);
        }
    }

    public function inventoryNo($id)
    {
        $inventory_no = Inventory::OfMaxno($id);

        if (!$inventory_no) {
            return Response::json([
                'error'=>true,
                'message'=>'Cannot Create Inventory Category',
                'code'=> 500
            ], 500);
        }else{
            return Response::json([
                'error'=>false,
                'message'=>'Successfuly Create Inventory Category',
                'code'=>200,
                'data'=>$inventory_no
            ], 200);
        }
    }

    public function getConverter($id)
    {
        $convert = InventoryConvert::where('inventory_code', $id)->get();

        return $convert;
    }

    public function storeConverter(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'inventory_code'=> 'required|string',
            'unit' => 'required|string',
            'size' => 'required|string',
        ]);
        if ($validator->fails()) {
            $messages = $validator->messages(); 

            return Response::json([
                'error'=>true,
                'message'=> $messages,
                'code'=> 500
            ], 404);
        }

        $convert = new InventoryConvert();
        $convert->inventory_code = $request->inventory_code;
        $convert->unit = $request->unit;
        $convert->size = $request->size;
        $convert->convert_type = $request->convert_type;
        $convert->save();

        if (!$convert) {
            return Response::json([
                'error'=>true,
                'message'=>'Cannot Create Inventory Convert',
                'code'=> 500
            ], 500);
        }else{
            return Response::json([
                'error'=>false,
                'message'=>'Successfuly Create Inventory Convert',
                'code'=>200,
                'data'=>$convert,
            ], 200);
        }
    }

    public function getPrice(Request $request,$id)
    {
        $price = InventoryPrice::where('inventory_code', $id)
                        ->orderBy('price_date','desc')
                        ->orderBy('price_unit','desc')
                        ->get();

        return $price;
    }

    public function storePrice(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'inventory_code'=> 'required|string',
            'price' => 'required|string',
        ]);
        if ($validator->fails()) {
            $messages = $validator->messages(); 

            return Response::json([
                'error'=>true,
                'message'=> $messages,
                'code'=> 500
            ], 404);
        }

        // 'stock_code','price','outlet_code'
        $price = new InventoryPrice();
        $price->inventory_code = $request->inventory_code;
        $price->price = $request->price;
        $price->price_unit = $request->price_unit;
        $price->price_date = $request->price_date;
        $price->save();

        if (!$price) {
            return Response::json([
                'error'=>true,
                'message'=>'Cannot Create Inventory Price',
                'code'=> 500
            ], 500);
        }else{
            return Response::json([
                'error'=>false,
                'message'=>'Successfuly Create Inventory Price',
                'code'=>200,
                'data'=>$price,
            ], 200);
        }
    }

    public function getDiscount($id)
    {
        $disc = InventoryDiscount::where('inventory_code', $id)->get();

        return $disc;
    }

    public function storeDiscount(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'inventory_code'=> 'required|string',
            'discount' => 'required|string',
        ]);
        if ($validator->fails()) {
            $messages = $validator->messages(); 

            return Response::json([
                'error'=>true,
                'message'=> $messages,
                'code'=> 500
            ], 404);
        }

        $disc = new InventoryDiscount();
        $disc->inventory_code = $request->inventory_code;
        $disc->discount = $request->discount;
        $disc->save();

        if (!$disc) {
            return Response::json([
                'error'=>true,
                'message'=>'Cannot Create Inventory Discount',
                'code'=> 500
            ], 500);
        }else{
            return Response::json([
                'error'=>false,
                'message'=>'Successfuly Create Inventory Discount',
                'code'=>200,
                'data'=>$disc,
            ], 200);
        }
    }

    public function getQuantity($id)
    {
        $qty = InventoryQuantity::where('inventory_code', $id)->get();

        return $qty;
    }

    public function storeQuantity(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'inventory_code'=> 'required|string',
            'outlet_code' => 'required|string',
        ]);

        if ($validator->fails()) {
            $messages = $validator->messages(); 

            return Response::json([
                'error'=>true,
                'message'=> $messages,
                'code'=> 500
            ], 404);
        }
        
        if ($request->qty_min != '') {
            $quantity = new InventoryQuantity();
            $quantity->inventory_code = $request->inventory_code;
            $quantity->qty_type = 'min';
            $quantity->qty = $request->qty_min;
            $quantity->save();
        }

        if ($request->qty_max != '') {
            $quantity2 = new InventoryQuantity();
            $quantity2->inventory_code = $request->inventory_code;
            $quantity2->qty_type = 'max';
            $quantity2->qty = $request->qty_max;
            $quantity2->save();
        }

        if (!$quantity) {
            return Response::json([
                'error'=>true,
                'message'=>'Cannot Create Inventory Quantity',
                'code'=> 500
            ], 500);
        }else{
            return Response::json([
                'error'=>false,
                'message'=>'Successfuly Create Inventory Quantity',
                'code'=>200,
                'data'=>$quantity,
            ], 200);
        }
    }

    public function chartPurchasingStock(Request $request)
    {   
        $begin = $request->input('begin');
        $end = $request->input('end');
        $inventory = $request->inventory;

        if(!$begin && !$end)
        {
            $now = date('Y-m-');
            $d1 = cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y'));
            $begin = new \DateTime($now.'01');
            $end = new \DateTime($now.$d1);
        }else{
            $begin = new \DateTime($begin);
            $end = new \DateTime($end);
        }

        $inventory_code = PurchasingDetail::select(
                        'calendars.datefield as DATE',
                        DB::raw('IFNULL(SUM(CASE WHEN purchasing_details.inventory_code="'.$inventory.'" THEN detail_qty ELSE 0 END),0) as total_qty'))
                ->rightJoin('calendars', DB::raw("DATE_FORMAT(purchasing_details.detail_date, '%Y-%m-%d')"), '=', 'calendars.datefield')

resources/views/inventory/colorant/create.blade.php
@extends('layouts.admin.admin')

@section('content-header')
	<section class="content-header">
      <h1>
        <i class="fa fa-newspaper-o"></i> Colorant
        <small>Colorant Manajemen</small>
      </h1>
      <ol class="breadcrumb">
      	<li><a href="{{ route('inventory.colorant.index') }}">Colorant</a></li>
        <li class="active">Create</li>
      </ol>
    </section>
@stop

@section('content')
  <section class="content">
  	{!! Form::model($colorant = new \App\Colorant, ['route' => 'inventory.colorant.store','id'=>'formColorant']) !!}
    	@include('inventory.colorant._form',['edit'=>false])
    {!! Form::close() !!}
  </section>
  @include('inventory.colorant._modal')
@stop

@section('script')
  @include('inventory.colorant._js')
@stop

resources/views/inventory/colorant/index.blade.php
@extends('layouts.admin.admin')

@section('content-header')
	<section class="content-header">
      <h1>
        <i class="fa fa-newspaper-o"></i> Colorant
        <small>Colorant Manajemen</small>
      </h1>
      <ol class="breadcrumb">
      	<li><a href="{{ route('inventory.index') }}">Inventory</a></li>
        <li><a href="{{ route('inventory.colorant.index') }}">Colorant</a></li>
        <li class="active">Index</li>
      </ol>
    </section>
@stop

@section('content')
	<div class="row">
		<div class="col-md-12">
			<div class="box box-primary">
				<div class="box-header with-border">
				   <h3 class="box-title">Colorant</h3>
				   <div class="box-tools pull-right">
				      <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
				      <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
				   </div>
				</div>

				<div class="box-body">
					<div class="col-md-12 box-body-header">
					   <div class="col-md-8">
					      <a href="{{ route('inventory.colorant.create') }}" class="btn btn-default">
					      	<i class="fa fa-plus" aria-hidden="true"></i> New
					      </a>
					      <button type="button" class="btn btn-default" onclick="deleteColorant()">
					      <i class="fa fa-times" aria-hidden="true"></i> Delete
					      </button>
					   </div>
					   <div class="col-md-4">
					      <input type="text" id="searchDtbox" class="form-control" placeholder="Search">
				   		</div>
					</div>

					{{-- {!! Form::open(['route'=>'inventory.colorant.delete', 'id'=>'formDeleteColorant']) !!} --}}
					<div>
						
					<table class="table table-bordered table-striped table-color" id="tableColorant">
						<thead>
							<th><input type="checkbox" id="check_all"></th>
							<th>Colorant Code</th>
							<th>Name</th>
							<th>Merk</th>
							<th>Unit</th>
							<th>Capacity</th>
							<th>Min. Capacity</th>
							<th>Max. Capacity</th>
							<th>Action</th>
						</thead>
						<tbody>
							@foreach($colorant as $c)
								<tr>
									<td>
										<input type="checkbox" id="idTableColorant" name="id[]" class="checkin" value="{{ $c->id }}">
									</td>
									<td><b>{{ $c->colorant_code }}</b></td>
									<td>{{ $c->name }}</td>
									<td>{{ $c->merks->name }}</td>
									<td>{{ $c->unit_stock }}</td>
									<td>{{ $c->capacity }}</td>
									<td>{{ $c->min_capacity }}</td>
									<td>{{ $c->max_capacity }}</td>
									<td>
										<a href="{{ route('inventory.colorant.edit', $c->id) }}" class="btn btn-default btn-xs">
											<i class="fa fa-pencil-square"></i> Edit
										</a>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
					{!! Form::close() !!}
					</div><!-- box body -->
				</div>
			</div>
		</div>
	</div>

	@include('master.supplier._modal')
@stop

@section('scripts')
	<script type="text/javascript">
		var tableColorant = $('#tableColorant').DataTable({
			// "sDom": 'rt',
   //    		"columnDefs": [{
   //      		"targets": [],
   //      		// "orderable": false,

   //    		}],
   //    		"stateSave": true,
   		"dom": "rtip",
          "pageLength": 10,
          "retrieve": true,
		});
		$("#searchDtbox").keyup(function() {
      		tableColorant.search($(this).val()).draw();
    	});
    	$('#tableColorant tbody').on('dblclick', 'tr', function () {
      		if ( $(this).hasClass('selected') ) {
        		$(this).removeClass('selected');
      		}
	      	else {
	        	tableColorant.$('tr.selected').removeClass('selected');
	        	$(this).addClass('selected');
	        	var id = $(this).find('#idTableSupplier').val();
	          	window.location.href = "/inventory/colorant/"+id+"/edit";
	      	}
    	});
    	function deleteColorant() {
			if ($('.checkin').is(':checked')) 
			{
				$('#deleteColorantModal').modal("show");
			} else {
				$('#deleteNoModal').modal("show");
				}
		}
		function DeleteColorant() {
			$("#formDeleteColorant").submit();
		}
	</script>
@stop